---
all:
  children:
    ubuntu:
      hosts:
        host_01:
          ansible_ssh_host: ip_address
          ansible_ssh_port: 22
        host_02:
          ansible_ssh_host: ip_addres
          ansible_ssh_port: 22
        host_03:
          ansible_ssh_host: ip_addres
          ansible_ssh_port: 22
